[package]
name = "werecat"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = "thin"

[profile.wasm-release]
inherits = "release"
opt-level = "s"
strip = "debuginfo"

[dependencies.bevy]
version = "0.16"
default-features = false
features = [
	"std",
	"multi_threaded",
	"bevy_asset",
	"bevy_render",
	"bevy_winit",
	"bevy_window",
	"wayland",
]
